### PR TITLE
feat: apply all changes

### PR DESCRIPTION
**Pull request by NassiHarel**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/worker-data-adapter.hkube/9)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 15 of 16 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/worker-data-adapter.hkube/9)* status: all files reviewed, 4 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[lib/cache/cache.js, line 1 at r2](https://reviewable.io/reviews/kube-hpc/worker-data-adapter.hkube/9#-MHvXXOd6TE_21_shEuC:-MHvXXOe7MYmKiuD8uiN:bo71ah4) ([raw file](https://github.com/kube-hpc/worker-data-adapter.hkube/blob/83df426ae85ef182c4b8d38752b2d941e22a2944/lib/cache/cache.js#L1)):*
> ```JavaScript
> const MB = 1000 * 1000;
> ```

not 1024? :-)
___
*[lib/cache/cache.js, line 14 at r2](https://reviewable.io/reviews/kube-hpc/worker-data-adapter.hkube/9#-MHvY2V_1wqJxZKd4CYA:-MHvY2V_1wqJxZKd4CYB:b1hpgva) ([raw file](https://github.com/kube-hpc/worker-data-adapter.hkube/blob/83df426ae85ef182c4b8d38752b2d941e22a2944/lib/cache/cache.js#L14)):*
> ```JavaScript
>             return true;
>         }
>         while ((this._size + size) >= this._maxCacheSize) {
> ```

It is the same in python, but I think that if the size of the data is larger than the cache size, just print the warning and return. no need to empty the cache and then find out it is too large
___
*[lib/communication/adapters/zeroMQ/server.js, line 8 at r2](https://reviewable.io/reviews/kube-hpc/worker-data-adapter.hkube/9#-MHvZlaPDo6jqLb-MWQJ:-MHvZlaPDo6jqLb-MWQK:b-8n4dlg) ([raw file](https://github.com/kube-hpc/worker-data-adapter.hkube/blob/83df426ae85ef182c4b8d38752b2d941e22a2944/lib/communication/adapters/zeroMQ/server.js#L8)):*
> ```JavaScript
>     listen(port, createReply) {
>         return new Promise((resolve, reject) => {
>             this._socket = zmq.socket('rep');
> ```

No need for linger=0 here?
___
*[lib/communication/adapters/zeroMQ/server.js, line 44 at r2](https://reviewable.io/reviews/kube-hpc/worker-data-adapter.hkube/9#-MHvZxYZ56YtX1j96NFS:-MHvZxYZ56YtX1j96NFT:b-rb2331) ([raw file](https://github.com/kube-hpc/worker-data-adapter.hkube/blob/83df426ae85ef182c4b8d38752b2d941e22a2944/lib/communication/adapters/zeroMQ/server.js#L44)):*
> ```JavaScript
>     _send(message) {
>         return new Promise((resolve, reject) => {
>             this._socket.send(message, null, (err, data) => {
> ```

you can use promisify

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/worker-data-adapter.hkube/9)* status: 12 of 16 files reviewed, 4 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[lib/cache/cache.js, line 1 at r2](https://reviewable.io/reviews/kube-hpc/worker-data-adapter.hkube/9#-MHvXXOd6TE_21_shEuC:-MHyv090EAwSKF7hol7l:b-896fix) ([raw file](https://github.com/kube-hpc/worker-data-adapter.hkube/blob/83df426ae85ef182c4b8d38752b2d941e22a2944/lib/cache/cache.js#L1)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

not 1024? :-)
</blockquote></details>

Done.
___
*[lib/cache/cache.js, line 14 at r2](https://reviewable.io/reviews/kube-hpc/worker-data-adapter.hkube/9#-MHvY2V_1wqJxZKd4CYA:-MHyv1B76vUSkHQYfWlB:b-896fix) ([raw file](https://github.com/kube-hpc/worker-data-adapter.hkube/blob/83df426ae85ef182c4b8d38752b2d941e22a2944/lib/cache/cache.js#L14)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

It is the same in python, but I think that if the size of the data is larger than the cache size, just print the warning and return. no need to empty the cache and then find out it is too large
</blockquote></details>

Done.
___
*[lib/communication/adapters/zeroMQ/server.js, line 8 at r2](https://reviewable.io/reviews/kube-hpc/worker-data-adapter.hkube/9#-MHvZlaPDo6jqLb-MWQJ:-MHyv47X25xSGhrPN0tB:b-896fix) ([raw file](https://github.com/kube-hpc/worker-data-adapter.hkube/blob/83df426ae85ef182c4b8d38752b2d941e22a2944/lib/communication/adapters/zeroMQ/server.js#L8)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

No need for linger=0 here?
</blockquote></details>

Done.
___
*[lib/communication/adapters/zeroMQ/server.js, line 44 at r2](https://reviewable.io/reviews/kube-hpc/worker-data-adapter.hkube/9#-MHvZxYZ56YtX1j96NFS:-MHyjhop4LxC1b0Ovt3v:bu7tsgq) ([raw file](https://github.com/kube-hpc/worker-data-adapter.hkube/blob/83df426ae85ef182c4b8d38752b2d941e22a2944/lib/communication/adapters/zeroMQ/server.js#L44)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

you can use promisify
</blockquote></details>

I can...

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/worker-data-adapter.hkube/9#-:-MHz0xiB21wfcuOEIZvY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @golanha)

**Review by golanha — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/worker-data-adapter.hkube/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @golanha)

**Pull request merged**
